import os
import uuid
from datetime import datetime
from typing import Optional
from app.core.config import settings

# ─── PDF Export ───────────────────────────────────────────────────────────────

def export_to_pdf(content: str, title: str, author: Optional[str] = None) -> str:
    """Generate a PDF file from document content. Returns file path."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch, cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

    filename = f"{uuid.uuid4().hex}.pdf"
    filepath = os.path.join(settings.OUTPUT_DIR, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=16,
        spaceAfter=12,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#1a1a2e"),
        fontName="Helvetica-Bold",
    )

    header_style = ParagraphStyle(
        "CustomHeader",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#666666"),
        alignment=TA_CENTER,
        spaceAfter=4,
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=16,
        spaceAfter=8,
        alignment=TA_JUSTIFY,
        fontName="Helvetica",
    )

    story = []

    # Header branding
    story.append(Paragraph("RAAM TECHLINK Pvt Ltd - Legal Document Platform", header_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 0.3 * cm))

    # Document title
    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, 0.2 * cm))

    # Generated date
    gen_date = f"Generated on: {datetime.now().strftime('%d %B %Y at %I:%M %p')}"
    if author:
        gen_date += f" | Prepared for: {author}"
    story.append(Paragraph(gen_date, header_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 0.5 * cm))

    # Document content - split by lines
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.2 * cm))
            continue

        # Detect headings (ALL CAPS lines)
        if line.isupper() and len(line) > 3:
            heading_style = ParagraphStyle(
                "SectionHeading",
                parent=styles["Normal"],
                fontSize=11,
                fontName="Helvetica-Bold",
                spaceBefore=8,
                spaceAfter=4,
                textColor=colors.HexColor("#1a1a2e"),
            )
            story.append(Paragraph(line, heading_style))
        else:
            # Escape HTML special chars
            safe_line = (
                line.replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
            )
            story.append(Paragraph(safe_line, body_style))

    # Footer disclaimer
    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#999999"),
        alignment=TA_CENTER,
        spaceAfter=2,
    )
    story.append(Paragraph(
        "This document was generated by the RAAM TECHLINK Legal Platform. "
        "Please review with a qualified legal professional before execution.",
        disclaimer_style,
    ))

    doc.build(story)
    return filepath


# ─── DOCX Export ──────────────────────────────────────────────────────────────

def export_to_docx(content: str, title: str, author: Optional[str] = None) -> str:
    """Generate a DOCX file from document content. Returns file path."""
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    filename = f"{uuid.uuid4().hex}.docx"
    filepath = os.path.join(settings.OUTPUT_DIR, filename)

    doc = Document()

    # Page margins
    section = doc.sections[0]
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)

    # Header branding
    header = doc.sections[0].header
    header_para = header.paragraphs[0]
    header_para.text = "RAAM TECHLINK Pvt Ltd | Legal Document Platform"
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    header_para.runs[0].font.size = Pt(8)
    header_para.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    # Document title
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run(title)
    run.font.size = Pt(16)
    run.font.bold = True
    run.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    # Generated date
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_text = f"Generated on: {datetime.now().strftime('%d %B %Y at %I:%M %p')}"
    if author:
        date_text += f" | Prepared for: {author}"
    run = date_para.add_run(date_text)
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()  # Spacer

    # Document content
    for line in content.split("\n"):
        if not line.strip():
            doc.add_paragraph()
            continue

        para = doc.add_paragraph()

        if line.strip().isupper() and len(line.strip()) > 3:
            run = para.add_run(line.strip())
            run.font.bold = True
            run.font.size = Pt(11)
            run.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)
        else:
            run = para.add_run(line)
            run.font.size = Pt(10)
            para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

    # Footer disclaimer
    doc.add_paragraph()
    disclaimer = doc.add_paragraph()
    disclaimer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = disclaimer.add_run(
        "This document was generated by the RAAM TECHLINK Legal Platform. "
        "Please review with a qualified legal professional before execution."
    )
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    run.font.italic = True

    doc.save(filepath)
    return filepath
